# DO NOT EDIT! This file is generated automatically!

# associative memory for linking references
# A → β
define([intro.mc.cs.capt], [Generování kódu v M4: úvod])
define([intro.mc.cs.anch], [generovani-kodu-v-m4-uvod])
define([1.cs.capt], [Generování kódu v M4: úvod])
define([1.cs.anch], [generovani-kodu-v-m4-uvod])
define([#.cs.Generování kódu v M4: úvod], [1])

# captions and ID
# A → β
define([intro.mc.cs.anch.Úvod], [uvod])
define([intro.mc.cs.uniq.Úvod])
define([intro.mc.cs.anch.Příklady pro čtenáře], [priklady-pro-ctenare])
define([intro.mc.cs.uniq.Příklady pro čtenáře])
define([intro.mc.cs.anch.Historie makro jazyků], [historie-makro-jazyku])
define([intro.mc.cs.uniq.Historie makro jazyků])
define([intro.mc.cs.anch.GPM (General Purpose Macro-generator)], [gpm-general-purpose-macro-genera])
define([intro.mc.cs.uniq.GPM (General Purpose Macro-generator)])
define([intro.mc.cs.anch.M3], [m3])
define([intro.mc.cs.uniq.M3])
define([intro.mc.cs.anch.M4], [m4])
define([intro.mc.cs.uniq.M4])
define([intro.mc.cs.anch.the_authors], [the-authors])
define([intro.mc.cs.anch.GNU M4], [gnu-m4])
define([intro.mc.cs.uniq.GNU M4])
define([intro.mc.cs.anch.install], [install])
define([intro.mc.cs.anch.Základy jazyka M4], [zaklady-jazyka-m4])
define([intro.mc.cs.uniq.Základy jazyka M4])
define([intro.mc.cs.capt.context_free_grammar], [Bezkontextová gramatika])
define([intro.mc.cs.anch.context_free_grammar], [bezkontextova-gramatika])
define([intro.mc.cs.uniq.Bezkontextová gramatika])
define([intro.mc.cs.capt.m4_rules], [Přepisovací pravidla M4])
define([intro.mc.cs.anch.m4_rules], [prepisovaci-pravidla-m4])
define([intro.mc.cs.uniq.Přepisovací pravidla M4])
define([intro.mc.cs.capt.expansion_control], [Řízení expanze neterminálů])
define([intro.mc.cs.anch.expansion_control], [rizeni-expanze-neterminalu])
define([intro.mc.cs.uniq.Řízení expanze neterminálů])
define([intro.mc.cs.capt.automata_descr], [Automaty])
define([intro.mc.cs.anch.automata_descr], [automaty])
define([intro.mc.cs.uniq.Automaty])
define([intro.mc.cs.capt.output_queues], [Výstupní fronty])
define([intro.mc.cs.anch.output_queues], [vystupni-fronty])
define([intro.mc.cs.uniq.Výstupní fronty])
define([intro.mc.cs.capt.main_uses_of_m4], [Hlavní použití M4])
define([intro.mc.cs.anch.main_uses_of_m4], [hlavni-pouziti-m4])
define([intro.mc.cs.uniq.Hlavní použití M4])
define([intro.mc.cs.capt.code_generation], [Generování kódu])
define([intro.mc.cs.anch.code_generation], [generovani-kodu])
define([intro.mc.cs.uniq.Generování kódu])
define([intro.mc.cs.anch.files_on_command_line], [files-on-command-line])
define([intro.mc.cs.capt.m4_as_preproc], [Preprocesor])
define([intro.mc.cs.anch.m4_as_preproc], [preprocesor])
define([intro.mc.cs.uniq.Preprocesor])
define([intro.mc.cs.anch.Smíšený režim], [smiseny-rezim])
define([intro.mc.cs.uniq.Smíšený režim])
define([intro.mc.cs.capt.prerequisites_for_mastering], [Předpoklady pro zvládnutí M4])
define([intro.mc.cs.anch.prerequisites_for_mastering], [predpoklady-pro-zvladnuti-m4])
define([intro.mc.cs.uniq.Předpoklady pro zvládnutí M4])
define([intro.mc.cs.anch.Základy gramatik], [zaklady-gramatik])
define([intro.mc.cs.uniq.Základy gramatik])
define([intro.mc.cs.capt.formal_grammar_chomsky], [Formální gramatika (Chomského typu)])
define([intro.mc.cs.anch.formal_grammar_chomsky], [formalni-gramatika-chomskeho-typ])
define([intro.mc.cs.uniq.Formální gramatika (Chomského typu)])
define([intro.mc.cs.anch.Základy automatů], [zaklady-automatu])
define([intro.mc.cs.uniq.Základy automatů])
define([intro.mc.cs.capt.testing_automaton], [Testovací automat])
define([intro.mc.cs.anch.testing_automaton], [testovaci-automat])
define([intro.mc.cs.uniq.Testovací automat])
define([intro.mc.cs.anch.dfa_img], [dfa-img])
define([intro.mc.cs.capt.generating_automaton], [Generující automat])
define([intro.mc.cs.anch.generating_automaton], [generujici-automat])
define([intro.mc.cs.uniq.Generující automat])
define([intro.mc.cs.anch.(GNU) make], [gnu-make])
define([intro.mc.cs.uniq.(GNU) make])
define([intro.mc.cs.anch.Vim], [vim])
define([intro.mc.cs.uniq.Vim])
define([intro.mc.cs.anch.Talent a čas], [talent-a-cas])
define([intro.mc.cs.uniq.Talent a čas])
define([intro.mc.cs.capt.code_generation_examples], [Příklady generování kódu])
define([intro.mc.cs.anch.code_generation_examples], [priklady-generovani-kodu])
define([intro.mc.cs.uniq.Příklady generování kódu])
define([intro.mc.cs.capt.input_source_code], [Vstupní zdrojový kód])
define([intro.mc.cs.anch.input_source_code], [vstupni-zdrojovy-kod])
define([intro.mc.cs.uniq.Vstupní zdrojový kód])
define([intro.mc.cs.anch.CODE_M4([[]]) CSV – nejjednodušší příklad], [csv-nejjednodussi-priklad])
define([intro.mc.cs.uniq.CODE_M4([[]]) CSV – nejjednodušší příklad])
define([intro.mc.cs.anch.CODE_M4([[]]) CSV – počítadlo], [csv-pocitadlo])
define([intro.mc.cs.uniq.CODE_M4([[]]) CSV – počítadlo])
define([intro.mc.cs.anch.CODE([💡], [řešení]) Speciální znaky výstupního kódu], [specialni-znaky-vystupniho-kodu])
define([intro.mc.cs.uniq.CODE([💡], [řešení]) Speciální znaky výstupního kódu])
define([intro.mc.cs.capt.modified_input_source_code], [Upravený vstupní kód])
define([intro.mc.cs.anch.modified_input_source_code], [upraveny-vstupni-kod])
define([intro.mc.cs.uniq.Upravený vstupní kód])
define([intro.mc.cs.anch.CODE_M4([[]]) XML[,] XSLT[,] HTML], [xml-xslt-html])
define([intro.mc.cs.uniq.CODE_M4([[]]) XML[,] XSLT[,] HTML])
define([intro.mc.cs.anch.CODE_M4([[]]) C[,] JSON[,] INI – CODE([DQ()řetězec[]DQ()])], [c-json-ini-dretezecd])
define([intro.mc.cs.uniq.CODE_M4([[]]) C[,] JSON[,] INI – CODE([DQ()řetězec[]DQ()])])
define([intro.mc.cs.anch.CODE_M4([[]]) Bash – CODE([DQ()řetězec[]DQ()])], [bash-dretezecd])
define([intro.mc.cs.uniq.CODE_M4([[]]) Bash – CODE([DQ()řetězec[]DQ()])])
define([intro.mc.cs.anch.CODE_M4([[]]) Bash – CODE([AP()řetězec[]AP()])], [bash-aretezeca])
define([intro.mc.cs.uniq.CODE_M4([[]]) Bash – CODE([AP()řetězec[]AP()])])
define([intro.mc.cs.anch.CODE_M4([[]]) CSV[,] M4], [csv-m4])
define([intro.mc.cs.uniq.CODE_M4([[]]) CSV[,] M4])
define([intro.mc.cs.anch.CODE_M4([[]]) C – výstupní fronta], [c-vystupni-fronta])
define([intro.mc.cs.uniq.CODE_M4([[]]) C – výstupní fronta])
define([intro.mc.cs.anch.CODE_M4([[]]) INI – externí příkaz], [ini-externi-prikaz])
define([intro.mc.cs.uniq.CODE_M4([[]]) INI – externí příkaz])
define([intro.mc.cs.anch.CODE_M4([[]]) .h – hex počítadlo], [h-hex-pocitadlo])
define([intro.mc.cs.uniq.CODE_M4([[]]) .h – hex počítadlo])
define([intro.mc.cs.capt.small_automaton], [CODE_M4([[]]) C – malý automat])
define([intro.mc.cs.anch.small_automaton], [c-maly-automat])
define([intro.mc.cs.uniq.CODE_M4([[]]) C – malý automat])
define([intro.mc.cs.anch.CODE_M4([[]]) C – malý automat 2], [c-maly-automat-2])
define([intro.mc.cs.uniq.CODE_M4([[]]) C – malý automat 2])
define([intro.mc.cs.capt.output_queues_html], [CODE_M4([[]]) HTML – výstupní fronty])
define([intro.mc.cs.anch.output_queues_html], [html-vystupni-fronty])
define([intro.mc.cs.uniq.CODE_M4([[]]) HTML – výstupní fronty])
define([intro.mc.cs.capt.branching_in_m4], [CODE_M4([[]]) Větvení gramatikou])
define([intro.mc.cs.anch.branching_in_m4], [vetveni-gramatikou])
define([intro.mc.cs.uniq.CODE_M4([[]]) Větvení gramatikou])
define([intro.mc.cs.capt.json_generating_automaton], [CODE_M4([[]]) JSON – generující automat])
define([intro.mc.cs.anch.json_generating_automaton], [json-generujici-automat])
define([intro.mc.cs.uniq.CODE_M4([[]]) JSON – generující automat])
define([intro.mc.cs.capt.json_branch], [CODE_M4([[]]) JSON – pojmenované fronty])
define([intro.mc.cs.anch.json_branch], [json-pojmenovane-fronty])
define([intro.mc.cs.uniq.CODE_M4([[]]) JSON – pojmenované fronty])
define([intro.mc.cs.anch.nonterminals_for_branches], [nonterminals-for-branches])
define([intro.mc.cs.capt.json_symbolic_queue_names], [CODE_M4([[]]) JSON – generované indexy front])
define([intro.mc.cs.anch.json_symbolic_queue_names], [json-generovane-indexy-front])
define([intro.mc.cs.uniq.CODE_M4([[]]) JSON – generované indexy front])
define([intro.mc.cs.anch.CODE_M4([[]]) INI – nespojitý index front], [ini-nespojity-index-front])
define([intro.mc.cs.uniq.CODE_M4([[]]) INI – nespojitý index front])
define([intro.mc.cs.anch.CODE_M4([[]]) XML – smíšené zprávy], [xml-smisene-zpravy])
define([intro.mc.cs.uniq.CODE_M4([[]]) XML – smíšené zprávy])
define([intro.mc.cs.anch.CODE_M4([[]]) XML – oddělené zprávy], [xml-oddelene-zpravy])
define([intro.mc.cs.uniq.CODE_M4([[]]) XML – oddělené zprávy])
define([intro.mc.cs.anch.CODE_M4([[]]) Bash CODE([CMD() echo []DQ()řetězec[]DQ()])], [bash-cmd-echo-dretezecd])
define([intro.mc.cs.uniq.CODE_M4([[]]) Bash CODE([CMD() echo []DQ()řetězec[]DQ()])])
define([intro.mc.cs.anch.CODE_M4([[]]) Bash CODE([CMD() echo 'řetězec'])], [bash-cmd-echo-aretezeca])
define([intro.mc.cs.uniq.CODE_M4([[]]) Bash CODE([CMD() echo 'řetězec'])])
define([intro.mc.cs.capt.preproc_examples], [Příklady preprocesoru])
define([intro.mc.cs.anch.preproc_examples], [priklady-preprocesoru])
define([intro.mc.cs.uniq.Příklady preprocesoru])
define([intro.mc.cs.capt.cpp_and_m4], [CODE_M4([`']) Preprocesor jazyka C[]NB()a[]NB()M4])
define([intro.mc.cs.anch.cpp_and_m4], [ba-preprocesor-jazyka-c-a-m4])
define([intro.mc.cs.uniq.CODE_M4([`']) Preprocesor jazyka C[]NB()a[]NB()M4])
define([intro.mc.cs.anch.CODE_M4([`']) CSS – komentáře], [ba-css-komentare])
define([intro.mc.cs.uniq.CODE_M4([`']) CSS – komentáře])
define([intro.mc.cs.capt.nprint_bash], [BO([CODE([␂␆])]) Bash – netisknutelné znaky])
define([intro.mc.cs.anch.nprint_bash], [bash-netisknutelne-znaky])
define([intro.mc.cs.uniq.BO([CODE([␂␆])]) Bash – netisknutelné znaky])
define([intro.mc.cs.capt.m4_on_examples], [M4 – příklady])
define([intro.mc.cs.anch.m4_on_examples], [m4-priklady])
define([intro.mc.cs.uniq.M4 – příklady])
define([intro.mc.cs.anch.CODE_M4([[]]) JSON – levá závorka CODE([LB()])], [json-leva-zavorka-b])
define([intro.mc.cs.uniq.CODE_M4([[]]) JSON – levá závorka CODE([LB()])])
define([intro.mc.cs.anch.CODE_M4([[]]) Bash – počítadla], [bash-pocitadla])
define([intro.mc.cs.uniq.CODE_M4([[]]) Bash – počítadla])
define([intro.mc.cs.capt.symbols_in_brackets], [CODE_M4([[]]) .h – závorky CODE_M4([[]])[,] CODE_M4([[,]])[,] CODE_M4([[#]])[,] CODE_M4([[dnl]])])
define([intro.mc.cs.anch.symbols_in_brackets], [h-zavorky-h-dnl])
define([intro.mc.cs.uniq.CODE_M4([[]]) .h – závorky CODE_M4([[]])[,] CODE_M4([[,]])[,] CODE_M4([[#]])[,] CODE_M4([[dnl]])])
define([intro.mc.cs.capt.safe_example], [CODE_M4([[]]) AWK – příklady bezpečnějších maker])
define([intro.mc.cs.anch.safe_example], [awk-priklady-bezpecnejsich-maker])
define([intro.mc.cs.uniq.CODE_M4([[]]) AWK – příklady bezpečnějších maker])
define([intro.mc.cs.capt.questions_and_answers], [Proč používat M4 a[]NB()proč ne?])
define([intro.mc.cs.anch.questions_and_answers], [proc-pouzivat-m4-a-proc-ne])
define([intro.mc.cs.uniq.Proč používat M4 a[]NB()proč ne?])
define([intro.mc.cs.capt.why_to_use_m4], [CODE([👍]) Proč generovat kód v[]NB()M4])
define([intro.mc.cs.anch.why_to_use_m4], [proc-generovat-kod-v-m4])
define([intro.mc.cs.uniq.CODE([👍]) Proč generovat kód v[]NB()M4])
define([intro.mc.cs.capt.why_not_use], [CODE([👎]) Proč se vyhnout M4])
define([intro.mc.cs.anch.why_not_use], [proc-se-vyhnout-m4])
define([intro.mc.cs.uniq.CODE([👎]) Proč se vyhnout M4])
define([intro.mc.cs.anch.low_level_language], [low-level-language])
define([intro.mc.cs.anch.forgotten_language], [forgotten-language])
define([intro.mc.cs.anch.unusual_language], [unusual-language])
define([intro.mc.cs.anch.experience_dependent], [experience-dependent])
define([intro.mc.cs.anch.hard_maintenance], [hard-maintenance])

# selected words from the current language
# A → β
define([cs.LANG_VERSION], [Česká verze])
